# Generated by Django 2.2 on 2019-05-14 18:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100, verbose_name='电影类型')),
                ('movienum', models.IntegerField(default=0, verbose_name='电影数量')),
            ],
            options={
                'verbose_name': '电影类型',
                'verbose_name_plural': '电影类型',
            },
        ),
        migrations.CreateModel(
            name='MovieSimilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.IntegerField(default=0, verbose_name='电影id')),
                ('item2', models.IntegerField(default=0, verbose_name='电影id')),
                ('similar', models.FloatField(default=0, verbose_name='相似度')),
            ],
            options={
                'verbose_name': '电影相似度信息',
                'verbose_name_plural': '电影相似度信息',
            },
        ),
        migrations.CreateModel(
            name='MovieSimilar_FromSpark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.IntegerField(default=0, verbose_name='电影id')),
                ('item2', models.IntegerField(default=0, verbose_name='电影id')),
                ('similar', models.FloatField(default=0, verbose_name='相似度')),
            ],
            options={
                'verbose_name': '电影相似度_spark计算',
                'verbose_name_plural': '电影相似度_spark计算',
            },
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(default='', max_length=1000, verbose_name='电影名称')),
                ('releasedate', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='上映年份')),
                ('nation', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='国家')),
                ('directors', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='导演')),
                ('leadactors', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='主演')),
                ('editors', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='编剧')),
                ('picture', models.CharField(blank=True, default='/static/images/m16.jpg', max_length=1000, null=True, verbose_name='缩略图')),
                ('averating', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='评分(0-5)')),
                ('numrating', models.IntegerField(blank=True, default=0, null=True, verbose_name='评分人数')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='简介')),
                ('backpost', models.CharField(blank=True, default='/static/images/2.jpg', max_length=3000, null=True, verbose_name='详情页海报')),
                ('typelist', models.ManyToManyField(to='movies.MovieCategory', verbose_name='类型')),
            ],
            options={
                'verbose_name': '电影信息',
                'verbose_name_plural': '电影信息',
            },
        ),
    ]
